import type { Product, LegacyStoreProfile } from "./types"

export const storeProfile: LegacyStoreProfile = {
  name: "Moda Latina",
  username: "@modalatina.store",
  avatar: "/fashion-store-logo-elegant.jpg",
  bio: "✨ Moda femenina | Envíos a todo el país | Pagos seguros",
  whatsappNumber: "5491123456789",
  instagramUrl: "https://instagram.com/modalatina.store",
}

export const categories = ["Todos", "Vestidos", "Blusas", "Pantalones", "Accesorios", "Zapatos"]

export const products: Product[] = [
  {
    id: "1",
    name: "Vestido Floral Verano",
    price: 4500,
    image: "/elegant-floral-summer-dress-fashion.jpg",
    images: ["/elegant-floral-summer-dress-fashion.jpg"],
    category: "Vestidos",
    description: "Vestido floral ligero perfecto para el verano. Tallas S, M, L",
    inStock: true,
  },
  {
    id: "2",
    name: "Blusa Elegante Satén",
    price: 2800,
    image: "/elegant-satin-blouse-women-fashion.jpg",
    images: ["/elegant-satin-blouse-women-fashion.jpg"],
    category: "Blusas",
    description: "Blusa de satén con detalles en encaje. Disponible en blanco y negro",
    inStock: true,
  },
  {
    id: "3",
    name: "Pantalón Wide Leg",
    price: 3900,
    image: "/wide-leg-pants-women-fashion-beige.jpg",
    images: ["/wide-leg-pants-women-fashion-beige.jpg"],
    category: "Pantalones",
    description: "Pantalón palazzo de tiro alto. Muy cómodo y versátil",
    inStock: true,
  },
  {
    id: "4",
    name: "Aretes Dorados Luna",
    price: 890,
    image: "/gold-moon-earrings-jewelry-elegant.jpg",
    images: ["/gold-moon-earrings-jewelry-elegant.jpg"],
    category: "Accesorios",
    description: "Aretes bañados en oro con diseño de luna creciente",
    inStock: true,
  },
  {
    id: "5",
    name: "Sandalias Platform",
    price: 5200,
    image: "/platform-sandals-women-fashion-beige.jpg",
    images: ["/platform-sandals-women-fashion-beige.jpg"],
    category: "Zapatos",
    description: "Sandalias con plataforma de 8cm. Muy cómodas",
    inStock: false,
  },
  {
    id: "6",
    name: "Vestido Midi Negro",
    price: 5800,
    image: "/black-midi-dress-elegant-women.jpg",
    images: ["/black-midi-dress-elegant-women.jpg"],
    category: "Vestidos",
    description: "Vestido midi elegante perfecto para ocasiones especiales",
    inStock: true,
  },
  {
    id: "7",
    name: "Collar Perlas Mini",
    price: 1200,
    image: "/pearl-necklace-elegant-jewelry-minimal.jpg",
    images: ["/pearl-necklace-elegant-jewelry-minimal.jpg"],
    category: "Accesorios",
    description: "Collar delicado con perlas cultivadas",
    inStock: true,
  },
  {
    id: "8",
    name: "Blusa Crop Lino",
    price: 2200,
    image: "/placeholder-x5aco.png",
    images: ["/placeholder-x5aco.png"],
    category: "Blusas",
    description: "Blusa crop de lino natural. Fresca y elegante",
    inStock: true,
  },
  {
    id: "9",
    name: "Tacones Stiletto",
    price: 6500,
    image: "/black-stiletto-heels-elegant-women-shoes.jpg",
    images: ["/black-stiletto-heels-elegant-women-shoes.jpg"],
    category: "Zapatos",
    description: "Tacones clásicos de 10cm. El básico perfecto",
    inStock: true,
  },
  {
    id: "10",
    name: "Jean Mom Fit",
    price: 4200,
    image: "/mom-fit-jeans-women-fashion-blue.jpg",
    images: ["/mom-fit-jeans-women-fashion-blue.jpg"],
    category: "Pantalones",
    description: "Jean tiro alto corte mom. Muy favorecedor",
    inStock: true,
  },
]
